// GraphQL operations will be generated by GraphQL Codegen
// placeholders

export const GET_CURRENT_USER = 'GetCurrentUser';
export const GET_FEED_POSTS = 'GetFeedPosts';
export const GET_POST_DETAILS = 'GetPostDetails';
export const GET_USER_PROFILE = 'GetUserProfile';
export const GET_POST_COMMENTS = 'GetPostComments';
export const LIKE_POST = 'LikePost';
export const SAVE_POST = 'SavePost';
export const CREATE_COMMENT = 'CreateComment';
export const FOLLOW_USER = 'FollowUser';
export const CREATE_POST = 'CreatePost';

